name: educonnect_mobile
description: "Mobile EduConnect App"
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS style UI
  cupertino_icons: ^1.0.8

  # ğŸ§© Base de donnÃ©es locale
  sqflite: ^2.3.3
  path: ^1.8.3
  pdfx: ^2.9.2   # ğŸ‘ˆ ajoute cette ligne ici
  google_fonts: ^6.2.1

  # âœ… Nouveau : Ã©criture dans TÃ©lÃ©chargements (Android 10+)
  file_saver: ^0.2.12
  # âœ… Nouveau : ouvrir le fichier tÃ©lÃ©chargÃ© dans un lecteur PDF
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lint rules
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pdfs/


  # Exemple pour les futurs assets
  # assets:
  #   - assets/images/
  #
  # Exemple pour les polices
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700