name: educonnect_mobile
description: "Mobile EduConnect App"
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS style UI
  cupertino_icons: ^1.0.8

  # ðŸ§© Base de donnÃ©es locale
  sqflite: ^2.3.3
  path: ^1.8.3
  http: ^1.2.2   # <--- AJOUTER ICI ///////////////////////
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lint rules
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/events/
    - assets/ml/metrics_best_model.json
    - assets/ml/best_model_succes.pkl


  # Exemple pour les futurs assets
  # assets:
  #   - assets/images/
  #
  # Exemple pour les polices
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
